---
    - name: Creating Docker Storage Configuration File
      template:
        src: docker-storage-setup.j2
        dest: "{{ dockerstorage }}"
        owner: root
        group: root
        mode: 755

    - name: Check if docker-vg exists
      stat:
        path: /dev/docker-vg
        get_md5: no
      register: dockervg_result
        
    - name: Creating Docker thin Pools and Configuring storage for docker Containers
      command: "docker-storage-setup"
      when: dockervg_result.stat.exists == False
