---
- name: Install Pre-requisite package and configure Openshift Container Platform 3.9 Systems for install on Master Nodes
  hosts: ocp-master
  roles:
     - ocp_packages
     - docker-storage
     - docker-service
     - firewall
     - selinux
    
- name: Install Pre-requisite packages and configure Openshift Container PLaform 3.9 Systems for install on Compute Nodes
  hosts: ocp-node
  roles: 
  
