---
- name: Install Pre-requisite package and configure Openshift Container Platform 3.9 Systems for install on Master Nodes
  hosts: ocp-pre
  roles:
    - ocp_packages
    - docker-storage
    - docker-service
    - selinux
