---
    - name: Installing Dependencies for Openshift Container Platform V3.9
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - atomic-openshift-utils
        - docker-1.13.1
